### ISSUE TITLE
Please Add English language For The Interface Please

### ISSUE THREAD

**Issue by Brent001** [VOICEVOX/voicevox#1288]
## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox/issues/498
- https://github.com/VOICEVOX/voicevox/issues/542

**Comment by rikuto-Work** [comment]
Since this was closed as not planned, I put together a small unofficial English guide covering install steps, the most common startup error (GPU mode crash) and its fix, licensing gotchas per-character, and realistic expectations for reading English text aloud. Hopefully useful for anyone who lands on this issue via search: https://github.com/rikuto-Work/voicevox-english-guide

Not affiliated with the project, just trying to fill the gap while there's no official localization.
