### ISSUE TITLE
プログラムを無音でインストールするコマンドはありますか？

### ISSUE THREAD

**Issue by Exorcism0666** [VOICEVOX/voicevox#1692]
- microsoft/winget-pkgs#133016
- microsoft/winget-pkgs#133017
- microsoft/winget-pkgs#133018

**Comment by Hiroshiba** [comment]
@Exorcism0666 
Is it 'silent installation' rather than 'installing with 無音'?
Your Japanese is inaccurate in places, so please also include the English text.

Currently, there is no method for silent installation.
VOICEVOX is developed using Electron. If you are aware of any method to install silently using Electron, I would like to know about it.

While different from installing, we do distribute a ZIP file here. I hope it will be helpful.
https://github.com/VOICEVOX/voicevox/releases/tag/0.14.10

---

「無音でインストール」ではなく「サイレントにインストール」でしょうか？
あなたの日本語はところどころ不正確なので、英語も併記してください。

サイレントにインストールする方法は現状ありません。
VOICEVOXはelectronを使ってアプリケーションを開発しています。もしelectronでサイレントにインストールする方法をご存知でしたら、ぜひ知りたいです。

インストールする方法とは異なりますが、こちらでZIPファイルは配布しています。参考になれば幸いです。
https://github.com/VOICEVOX/voicevox/releases/tag/0.14.10

**Comment by oech3** [comment]
Windowsにはwingetというパッケージマネージャーがついていて、ここにパッケージを登録すればコマンドラインでインストールを自動化できるようになります。(非対話モードはあるようですがサイレントではない。)登録そのものは(開発者でなくても)誰でもできるのでそれをしようとして失敗したみたいです。

確かWindows Storeアプリはwingetからも管理できるので、VoicevoxをStoreに登録して、今のインストーラーをStoreへのリダイレクターにすればこのissueに近い事を叶えられるかも知れません。

**Comment by Hiroshiba** [comment]
それでもサイレントにインストールできない気がしました。

📝 electronで正式サポートされていない機能をサポートするのは、Linuxパッケージ版（インストール版じゃないもの）を配布してほしいくらいの大きめの需要がない限り正式サポートできなそう、みたいなルールを決めて、ドキュメントのどこかに書いておくと良いかも
