### ISSUE TITLE
English Cross-lingual Support?

### ISSUE THREAD

**Issue by jikyusan** [VOICEVOX/voicevox#1991]
Hi. I would like to know if VOICEVOX would get English support.
I'd like to see an English UI.
Also, I would love to see Cross-lingual Support.
For example, I'd like to use Zundamon's VOICEVOX in English.
Dreamtronic's Synthesizer V created a cross-lingual feature using their deep learning research to make Japanese singing voices in other languages: (Japanese > English/Chinese)
Could something similar be created for VOICEVOX?

**Comment by Hiroshiba** [comment]
We're also interested in internationalizing the UI! Here's an issue about it; please take a look. If you're interested, try creating a part of it and show us! 
https://github.com/VOICEVOX/voicevox/issues/1682

We're interested in making the voices available in English too, but our current technology doesn't allow it. We need to develop new technologies for that, but we are stretched thin right now, so it won't be possible in the near future. However, we are enthusiastic about it. There's also a discussion in this issue, so take a look if you're interested!
https://github.com/VOICEVOX/voicevox/issues/542

Since there are existing similar issues, I will close this issue. By the way, we have a developer Discord; feel free to join it from the README. We sometimes discuss things related to English there.

---

UIの国際化は我々としても興味があります！
こちらにissueがあるのでご覧ください。もし興味があれば一部分だけ作ってみて僕たちに見せてください！
https://github.com/VOICEVOX/voicevox/issues/1682

音声の英語化も興味があるのですが、現状の技術ではできません。
そのため新しい技術の開発が必要ですが、手が回っていないので当面は無理でしょう。
ただ意欲はあります。このあたりのissueでも議論があるので、もし興味があればご覧ください！
https://github.com/VOICEVOX/voicevox/issues/542

どちらも既存の似たissueがあるのでこのissueはcloseします。
ちなみに開発者DiscordがあるのでよかったらREADMEから参加してみてください。
たまに英語に関するやりとりをしています。

**Comment by Patchethium** [comment]
I was working on UI i18n, but there're too many entries and I kinda lost my motivation. I've made a translation helper site:
https://vv-translation-helper.vercel.app/
If you can translate that, click the "Export File" on right top corner and upload the downloaded json here, I can merge it.
