### ISSUE TITLE
Do we really need user data?

### ISSUE THREAD

**Issue by Patchethium** [VOICEVOX/voicevox#687]
## Content

In #668 , another dialog urging the users to allow the collection of usage information is to be added, but is it really that necessary?

On one hand, we're not benefiting much from the collected data. As far as I know, no element was added/removed because of its usage, neither the data was referenced in comments since #567 was merged.

On the other hand, privacy **IS** a concern, even though users are able to review the code, collecting user data still appears to be sneaky, and may get users to distrust the software. As an example, after [Audacity](https://github.com/audacity/audacity) sold itself to a registered company and started collecting data, many users, including me, jumped to [one of its forks](https://github.com/tenacityteam/tenacity). Since there was actually a violation of privacy involved in Audacity, the situation won't get that bad here but it does suggest that we need to think twice before touching this part.

As a conclusion, I advice developers to concern more about the privacy issue. Do we really need to push further when we're not promised with more profit?

**Comment by Hiroshiba** [comment]
Analyzing software usage is useful for making choices in OSS development, where development costs are limited.
For example, if VOICEVOX becomes too complex in the future, it may happen that the maintenance of existing features is too difficult to implement new features.
In such a case, there is a way to reduce the maintenance debt by deleting some of the existing features, but without knowing the actual usage, it would be a wrong decision.

In fact, I have lost the trust of my users in the past when I deleted a button for user usability.
https://github.com/VOICEVOX/voicevox/issues/463
Based on this experience, I believe that analyzing software usage is beneficial for both users and developers.

> As a conclusion, I advice developers to concern more about the privacy issue.

Yes, I thought it was important to be more concerned about privacy issues.

If you don't mind me asking, what kind of distrust would you feel if software usage were to be submitted?
For example, I think text information could be a privacy issue since personal names and other information could be inputted.
Therefore, we do not collect any text information that is inputted.
What are your specific concerns?

---

ソフトウェアの利用状況を解析することは、開発コストがかなり限られているOSS開発において、機能開発の注力を取捨選択するのに役立っていると考えています。
たとえば将来VOICEVOXがあまりにも多機能になり、そのままだと既存機能のメンテナンスが大変すぎて新機能が実装できないことが起こるかもしれません。
その際、既存機能の一部を失くして保守的な負債を減らす手がありますが、実際の利用状況がわかっていないとどの機能であればユーザーからの理解が得られやすいのかがわかりづらいかもしれません。

実際、過去にユーザー操作性を考えてボタンを消去した際、ユーザーからの信頼を失ったことがあります。
https://github.com/VOICEVOX/voicevox/issues/463
この経験から、ソフトウェア利用状況を解析するのは、ユーザーにとっても開発者にとってもメリットのあることだと考えています。

> As a conclusion, I advice developers to concern more about the privacy issue.

たしかにプライバシー問題をもっと気にすることは大切なことだと思いました。

もしよかったら知りたいのですが、仮にソフトウェアの利用状況が送信される場合、どのような不信感を得ますか？
例えばテキスト情報は個人名などが入力される可能性があるので、プライバシー的に問題があると思います。
なので、入力したテキスト情報は一切収集していません。
具体的にどのようなことを懸念されていますか？

**Comment by Yosshi999** [comment]
Here is my opinions. I don't think these will not happen, but there is a probability.
* Some users (or followers of an influencer) may think we are stealing some confidential information **no matter what we (and Google) actually do**. They may have a distrust when they notice our software sends some packets to somewhere on Internet.
* Some skeptical users may have a distrust just because "Agree" button is easier to push than "Disagree".
* Some users dislike the Google's tracking system and they don't feel good when our application is using an analysis tool produced by Google.

**Comment by Patchethium** [comment]
> Therefore, we do not collect any text information that is inputted.

Well as I said, even if we're not doing something sneaky, it may appear to be. What concerns me is that I don't have the time to read every sentence in EULA or source code. And even if I did, I still don't know if it's obeyed.

> #463

Since #463 happened before #567 got merged, I don't think this can prove we're benefiting from the collected data, only that we may get some in the future. Which, as I mentioned above, is not that promising since no reference is made in last 2 months.

**Comment by Hiroshiba** [comment]
I see. I guess you could say this.
"Data collection has the risk of causing concern, but we are not getting any results that exceed that risk.
If that's the case, we should stop collecting data."

I realized that this was indeed a possibility.
But I would like to continue collecting data for a while, because maybe we can get some hints for new development.
Then, if we see a trend of increasing user concerns on SNS, or if we find that collecting the data is not very effective, how about we stop collecting the data immediately?

**Comment by Patchethium** [comment]
Closing because I don't have any objection. Sorry I forgot to do it earlier.
