### ISSUE TITLE
It renders the pitch accent of onomatopoeia incorrectly.

### ISSUE THREAD

**Issue by issuefiler** [VOICEVOX/voicevox#841]
### The environment

Portable, CUDA-based **VOICEVOX 0.12.3** on 64-bit Windows 10 Pro 10.0.19044 with NVIDIA GeForce GTX 1080 Ti.

### The problem

It renders the pitch accent of onomatopoeia incorrectly.

### The output

- **ふわふわ HLLL** / する LH
- **ふわふわの HLLLL**❌
- **ふわふわ HLLL** / した LH / ケーキ HLL
- ほんとうに LHHHH / **ふわふわの HLLLL**❌ / まくらだ。 HLLL

### The expected

- **ふわふわ HLLL** / する LH
- **ふわふわの LHHHH**✔️
- **ふわふわ HLLL** / した LH / ケーキ HLL
- ほんとうに LHHHH / **ふわふわの LHHHH**✔️ / まくらだ。 HLLL

**Comment by Patchethium** [comment]
It's up to the deep learning model behind the scene, which you can't expect to give perfect prediction. I recommend to tune the pitch yourself, the gui is here for a reason.

**Comment by Hiroshiba** [comment]
Thanks for creating the issue!

@Patchethium is right, this is due to OpenJTalk (and furthermore, the mecab within it and its dictionary) that VOICEVOX is utilizing.
There are probably many errors, and it is difficult to eliminate/maintain all of them.

Please correct them each time in the GUI or register the dictionary.

P.S.
There is also an Issue to collect dictionaries.
https://github.com/VOICEVOX/voicevox/issues/640
